package guru.sfg.beer.order.service.domain;

public enum BeerOrderEventEnum {
    VALIDATE_ORDER, VALIDATION_PASSED, VALIDATION_FAILED,
    ALLOCATE_ORDER, ALLOCATION_SUCCES, ALLOCATION_NO_INVENTORY, ALLOCATION_FAILED,
    BEEROREDER_PICKED_UP
}
